version: '3.8'

#To test, use in cmd :
#  - docker-compose build
#  - docker-compose up

services:
  backend:
    image: ${BACK_IMG_TAG}
    build:
      context: ./
      dockerfile: ./ps_back.Dockerfile
    container_name: ps_back
    environment:
      - SPRING_PROFILES_ACTIVE=${ENV}
      - SPRING_CONFIG_ADDITIONAL_LOCATION=/ps-back/conf/application-${ENV}.yml
    volumes:
      - ./application-${ENV}.yml:/ps-back/conf/application-${ENV}.yml
    networks:
      - ps_network

  frontend:
    image: ${FRONT_IMG_TAG}
    build:
      context: ./
      dockerfile: ./ps_front.Dockerfile
    container_name: ps_front
    ports:
      - "80:80"
    networks:
      - ps_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: >
      start-dev
            --http-port=8080
            --hostname-strict=false
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - "8081:8080"
    networks:
      - ps_network

volumes:
  keycloak_data:

networks:
  ps_network:
